# Generated by Django 3.0.3 on 2020-02-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20200210_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet_id',
            new_name='tweetId',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='user_name',
            new_name='userName',
        ),
    ]
